### ISSUE TITLE
Bug: Avatar copy & download menu not displaying on mobile 

### ISSUE THREAD

**Issue by mr3wi** [femi-Zedev/avatar-lustr#14]
https://github.com/femi-Zedev/avatar-lustr/assets/93126768/6cefe520-8246-4849-b0d1-0dff5682c5d5

**Comment by femi-Zedev** [comment]
@mr3wi  Merci d'attirer mon attention dessus

**Comment by mr3wi** [comment]
> @mr3wi Merci d'attirer mon attention dessus

De rien j'ai ouvert une PR pour le fix #15
