### ISSUE TITLE
Filtrage par sexe 

### ISSUE THREAD

**Issue by heyolaniran** [femi-Zedev/avatar-lustr#7]
Le filtrage s'applique en un clique quand je passe de Homme à Femme mais lors du clique sur Tous , la modification du rendu ne s'applique qu'au second clique.

**Comment by femi-Zedev** [comment]
> Le filtrage s'applique en un clique quand je passe de Homme à Femme mais lors du clique sur Tous , la modification du rendu ne s'applique qu'au second clique.

Merci @heyolaniran, j'ai gérer le filtre par sexe et par race dans la dernière PR que j'ai mergé.
